#!/bin/bash
sudo apt install fzf powerline powerline-gitstatus xbacklight terminator scrot trayer xmobar dmenu volumeicon-alsa feh xcompmgr gnome-settings-daemon xmonad keychain redshift-gtk jq arandr gnome-screensaver
