#!/bin/bash
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi
#xrdb -merge ~/.Xresources
#setxkbmap fr
gnome-screensaver &
gnome-settings-daemon &
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --alpha 0 --tint 0x555555 --height 17 & 

#gnome-sound-applet &
volumeicon &
nm-applet &

# Start XMonad
exec ck-launch-session xmonad
pkill -HUP ssh-agent
