#!/bin/bash
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

~/.screenlayout/glc.sh

#xrdb -merge ~/.Xresources
#setxkbmap fr
gnome-screensaver &
gnome-settings-daemon &
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --alpha 0 --tint 0x555555 --height 17 --monitor primary & 

#gnome-sound-applet &
#pulseaudio --start
volumeicon &
nm-applet &

feh --bg-scale /home/cyril/Images/wall.jpg
xcompmgr & 

xsetroot -cursor_name left_ptr

redshift-gtk &

# Start XMonad
exec  dbus-launch --sh-syntax --exit-with-session xmonad
pkill -HUP ssh-agent
